eureka:
  instance:
    prefer-id-address: true
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

okta:
  oauth2:
    issuer: https://dev-70515516.okta.com/oauth2/default
    audience: api://default
